ALTER TABLE Customers
ADD Email VARCHAR(100);

ALTER TABLE Customers
DROP COLUMN Email;

ALTER TABLE Customers
MODIFY COLUMN Phone VARCHAR(30);

ALTER TABLE Customers
RENAME COLUMN Name TO FullName;

ALTER TABLE Customers
ALTER COLUMN Phone VARCHAR(30);